### ISSUE TITLE
Unable to Compile with Birch..

### ISSUE THREAD

**Issue by echanna** [IONISx/edx-theme#40]
Hi, 

I downloaded the master zip, and renamed the folder to ionisx in the theme folder.  When I try to compile, I get this error:

python manage.py cms --settings=aws collectstatic --noinput > /dev/null
2015-03-26 14:14:18,912 INFO 24856 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 169, in handle_noargs
    collected = self.collect()
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 126, in collect
    for original_path, processed_path, processed in processor:
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/require/storage.py", line 172, in post_process
    for path in super_class.post_process(paths, dry_run, **options):
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 279, in post_process
    content = pattern.sub(converter, content)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 368607: ordinal not in range(128)

Captured Task Output:
---------------------

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py cms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/themes/ionisx /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name "*.coffee"`
sass --style compressed  --cache-location /tmp/sass-cache --load-path ./common/static/sass /edx/app/edxapp/themes/ionisx/static/sass --update -E utf-8 */static /edx/app/edxapp/themes/ionisx/static/sass
python manage.py cms --settings=aws collectstatic --noinput > /dev/null

Build failed running pavelib.assets.update_assets: Subprocess return code: 1

**Comment by tusbar** [comment]
@echanna,

The theme is only for the LMS. It’s not meant to work with Studio.

**Comment by echanna** [comment]
Hi,

With LMS, I still get this error:

python manage.py lms --settings=aws collectstatic --noinput > /dev/null
2015-03-26 15:35:00,942 INFO 11354 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 169, in handle_noargs
    collected = self.collect()
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 126, in collect
    for original_path, processed_path, processed in processor:
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 279, in post_process
    content = pattern.sub(converter, content)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 368607: ordinal not in range(128)


Captured Task Output:
---------------------

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py lms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/themes/ionisx /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name "*.coffee"`
sass --style compressed  --cache-location /tmp/sass-cache --load-path ./common/static/sass /edx/app/edxapp/themes/ionisx/static/sass --update -E utf-8 */static /edx/app/edxapp/themes/ionisx/static/sass
python manage.py lms --settings=aws collectstatic --noinput > /dev/null

Build failed running pavelib.assets.update_assets: Subprocess return code: 1

**Comment by echanna** [comment]
When I do bower install I am getting:

Stack trace:
Error: EACCES, mkdir '/edx/app/edxapp/themes/ionisx/bower_components'

Console trace:
Trace
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.37
OS: Linux 3.11.0-15-generic x64

**Comment by echanna** [comment]
I got arround the bower install problem by doing "sudo bower install --allow-root"

**Comment by echanna** [comment]
but I still get this error when compiling assets:

python manage.py lms --settings=aws collectstatic --noinput > /dev/null
2015-03-26 16:21:08,636 INFO 28185 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 169, in handle_noargs
    collected = self.collect()
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 126, in collect
    for original_path, processed_path, processed in processor:
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 279, in post_process
    content = pattern.sub(converter, content)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 368607: ordinal not in range(128)


Captured Task Output:
---------------------

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py lms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/themes/ionisx /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name "*.coffee"`
sass --style compressed  --cache-location /tmp/sass-cache --load-path ./common/static/sass /edx/app/edxapp/themes/ionisx/static/sass --update -E utf-8 */static /edx/app/edxapp/themes/ionisx/static/sass
python manage.py lms --settings=aws collectstatic --noinput > /dev/null

Build failed running pavelib.assets.update_assets: Subprocess return code: 1

**Comment by tusbar** [comment]
First of all, you don’t need to `bower install` on the server. The repository contains pre-built assets, so you just have to clone the repo or download a tarball, update Open edX configuration and just restart it (I’ll write a section on that in the readme ASAP).

Concerning your error, I’ve been able to reproduce, it’s an issue with `collectstatic` and non-ascii characters in static files.

I’m working on it, I’ll let you know when I find a fix.

**Comment by echanna** [comment]
OK thanks I will try that next.

**Comment by tusbar** [comment]
@echanna fixed in https://github.com/IONISx/edx-theme/releases/tag/v1.4.2
